import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mexsana Game App",
  description: "Generated by PressStartEvolution",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `window.__APP_CONFIG__ = {
              basePath: ${JSON.stringify(process.env.NEXT_PUBLIC_BASE_PATH || "/tbwa/mexana/game-runner")},
              remoteApiBaseUrl: ${JSON.stringify(process.env.NEXT_PUBLIC_REMOTE_API_BASE_URL || process.env.REMOTE_API_BASE_URL || "https://www.pressstartevolution.com/tbwa/mexana/admin/apigame/")},
              basicAuthToken: ${JSON.stringify(process.env.NEXT_PUBLIC_BASIC_AUTH_TOKEN || process.env.BASIC_AUTH_TOKEN || "UHJlc3NzdGFydGV2b2x1dGlvbjpQcjNzdCQkMjAyNQ==")}
            };`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
